version: '3.8'

services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: jenkins_golang
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - TZ=America/Manaus

volumes:
  jenkins_home:
    name: jenkins_home_volume
